# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Johan Driessen
subtitle: Programming, old tech and other stuff that interest me
description:
keywords:
author: Johan Driessen
author_info: "My name is Johan Driessen. I work as a consultant and developer at Approach. These are good ways to get in touch with me:"
#language:
#timezone:

disqus_shortname: johansblog

contact:
  twitter:
  bluesky: nahojd.bsky.social
  mastodon: mastodon.social/@nahojd
  github: nahojd
  linkedin: johandriessen
  facebook: johan.driessen

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://johan.driessen.se
root: /
permalink: posts/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

include:
  - .well-known/**/*

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: landscape

# https://github.com/hexojs/hexo-generator-feed
feed:
  type: rss2
  path: feed/rss.xml
  limit: 15
  hub:
  content: true
#  content_limit: 140
#  content_limit_delim: ' '
  order_by: -date
  icon:

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:
